export const products = [
    {
        _id: '1',
        name: 'Boat Airdopes 121v2 Earbuds',
        image: '/images/phone.png',
        description: 'asd fgh thjk ahuf  ahfd f fdfgfghghghj dfgdgdhfgfdfg',
        brand: 'Boat',
        category: 'Electronics',
        price: 10.99,
        countInStock: 10,
        rating: 2,
        numReviews: 11,
    },
    {
        _id: '2',
        name: 'Boat Airdopes 121v2 Earbuds',
        image: '/images/phone.png',
        description: 'asd fgh thjk ahuf  ahfd f fdfgfghghghj dfgdgdhfgfdfg',
        brand: 'Boat',
        category: 'Electronics',
        price: 20.99,
        countInStock: 10,
        rating: 5,
        numReviews: 12,
    },
    {
        _id: '3',
        name: 'Boat Airdopes 121v2 Earbuds',
        image: '/images/phone.png',
        description: 'asd fgh thjk ahuf  ahfd f fdfgfghghghj dfgdgdhfgfdfg',
        brand: 'Boat',
        category: 'Electronics',
        price: 30.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 13,
    },
    {
        _id: '4',
        name: 'Boat Airdopes 121v2 Earbuds',
        image: '/images/phone.png',
        description: 'asd fgh thjk ahuf  ahfd f fdfgfghghghj dfgdgdhfgfdfg',
        brand: 'Boat',
        category: 'Electronics',
        price: 40.99,
        countInStock: 10,
        rating: 1.5,
        numReviews: 14,
    },
    {
        _id: '5',
        name: 'Boat Airdopes 121v2 Earbuds',
        image: '/images/phone.png',
        description: 'asd fgh thjk ahuf  ahfd f fdfgfghghghj dfgdgdhfgfdfg',
        brand: 'Boat',
        category: 'Electronics',
        price: 50.99,
        countInStock: 10,
        rating: 3,
        numReviews: 15,
    },
    {
        _id: '6',
        name: 'Boat Airdopes 121v2 Earbuds',
        image: '/images/phone.png',
        description: 'asd fgh thjk ahuf  ahfd f fdfgfghghghj dfgdgdhfgfdfg',
        brand: 'Boat',
        category: 'Electronics',
        price: 60.99,
        countInStock: 10,
        rating: 3.5,
        numReviews: 16,
    },
    {
        _id: '7',
        name: 'Boat Airdopes 121v2 Earbuds',
        image: '/images/phone.png',
        description: 'asd fgh thjk ahuf  ahfd f fdfgfghghghj dfgdgdhfgfdfg',
        brand: 'Boat',
        category: 'Electronics',
        price: 70.99,
        countInStock: 10,
        rating: 5,
        numReviews: 17,
    },
    {
        _id: '8',
        name: 'Boat Airdopes 121v2 Earbuds',
        image: '/images/phone.png',
        description: 'asd fgh thjk ahuf  ahfd f fdfgfghghghj dfgdgdhfgfdfg',
        brand: 'Boat',
        category: 'Electronics',
        price: 80.99,
        countInStock: 10,
        rating: 4,
        numReviews: 18,
    },
    {
        _id: '9',
        name: 'Boat Airdopes 121v2 Earbuds',
        image: '/images/phone.png',
        description: 'asd fgh thjk ahuf  ahfd f fdfgfghghghj dfgdgdhfgfdfg',
        brand: 'Boat',
        category: 'Electronics',
        price: 90.99,
        countInStock: 10,
        rating: 4,
        numReviews: 19,
    },
];